server:
  port : 8761
eureka:
  instance:
    hostname : localhost
  server:
      renewal-percent-threshold: 0.85
      enable-self-preservation: false # 自我保护 如果不关闭，关掉的节点无法及时更新
      eviction-interval-timer-in-ms: 10000 # 清理列表间隔时间 清理间隔（单位毫秒，默认是60*1000）
      response-cache-update-interval-ms: 4000
  client:
    registerWithEureka : false
    fetchRegistry : false
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/