server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance_id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
logging:
  config:
    classpath: log4j2-spring.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource