server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://devops:devops#2019@localhost:8761/devops_eureka_server
  instance:
    prefer-ip-address: true
    instance_id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://114.115.205.121:3306/it_cloud_dm?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
#    username: root
#    password: root